### ISSUE TITLE
Predolgi seznami smeri

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/urnik#10]
Tako kot pri #9 tudi seznam smeri prekriva druge oznake. Morda bi ga kar ukinili, vsaj v natisnjeni varianti?

**Comment by jureslak** [comment]
Vmesna varianta, ki jo jaz uporabljam pri sebi, ko mi gredo naživce je

```
.letniki {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow-x: hidden;
 }
```
kar zavzame samo eno vrstico in jih potem ubije s ...
Bom se pa morda lotil reševanja positioninga znotraj boxa za srecanja, ker me se kar moti trenutna situacija.

**Comment by matijapretnar** [comment]
Ja, tole bi bila v redu varianta, ne samo za seznam smeri (ki bi ga vedno raje pobrisal) ampak tudi za imena predmetov.

**Comment by jureslak** [comment]
Sem naredil tak design, da je nemogoče, da se karkoli prekriva. Za predavatlja in učilnico je rezervirana samo spodnja vrstica, ki se spremeni v ellipsis, ce je predolgo. Ostali text je prost, z `overflow: hidden`. 

Nekoč sva govoria tudi o info boxu, za katerega sem že pozabil, zakaj bi ga rabili (poleg neskončne zaloge prostora), ampak je zakomentiran v kodi in zgleda tako:
![image](https://user-images.githubusercontent.com/1394590/36123469-01c39f04-104d-11e8-82a6-cd056457e418.png)
Text ga seveda obliva, če ga je več.

Prej:
![image](https://user-images.githubusercontent.com/1394590/36123121-0491fcf4-104c-11e8-9256-2ad53b62cdb4.png)

Potem:
![image](https://user-images.githubusercontent.com/1394590/36123167-264cce1e-104c-11e8-8e4d-2929d49c6e7f.png)

Prej: 
![image](https://user-images.githubusercontent.com/1394590/36123304-7e53e78c-104c-11e8-9026-845f3ca1a1dd.png)

Potem:
![image](https://user-images.githubusercontent.com/1394590/36123331-99e95298-104c-11e8-9ebd-a2e49b069989.png)
