### ISSUE TITLE
Poenostavitev tiskanja

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/urnik#11]
Urnik se tiska kar prek brskalnika, ampak ima par pomanjkljivosti:

- ljudje pogrešajo gumbek natisni - tu je verjetno treba napisati en kratek JavaScript
- pri tiskanju je treba vključiti tiskanje ozadij - ali se da v zgornjem JavaScriptu to že predlagati brskalniku?
- na začetku leta se tiska veliko urnikov - bi se dalo narediti le en HTML z ustreznimi prelomi strani?

**Comment by jureslak** [comment]
* ja, ljudje ne znajo uporabljati `ctrl-P`. Ampak ja, z lahkoto, je zelo kratek `<a onclick="window.print()">`
* To je odvisno od stila za printanje, morda #16 reši to težavo? Sicer pa dvomim, v meniju se sicer lahko to izbere, ampak nisem zasledil da bi to lahko predizbral. Se pa da pohackat s css borderji, ce je res treba :)
* hmm, tega nisem predlagal na glas, ampak ja, pomoje precej lahko z eno stranjo z ogromno iframe-i, ki odprejo vse urnike kot podstrani
