### ISSUE TITLE
Kazalo na stran z odprtimi zadevami

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/urnik#12]
Na strani za urnik bi bilo na dnu treba dodati povezavo na [GitHub stran z odprtimi zadevami](https://github.com/ul-fmf/urnik/issues/). Tako ljudje vidijo, da skrbnik že dolgo časa ve za vse njihove želje, vendar je prelen, da bi karkoli naredil glede njih. Ob povezavi bi bila tudi kratka navodila v stilu: 

> Seznam želja in napak lahko najdete na … - če želite še kakšno dodati, jo pošljite na mail … ali pa se prijavite na GitHub in jo [vpišite kar sami](https://github.com/ul-fmf/urnik/issues/new/) - v tem primeru lahko tudi sodelujete v diskusiji

**Comment by matijapretnar** [comment]
Predlagam, da je namesto gumba samo tekst v footerju. Se mi zdi, da je to najbolj enostavno, da so ljudje na to navajeni, pa tudi na hodniku lahko na hitro rečem "poglej navodila na dnu strani" namesto "spodaj desno, razen če si na telefonu, je gumb in če se zapelješ gor, dobiš navodila in potem lahko klikneš, samo ne zapelji se malo stran, ker bodo izginila, pa lahko tudi pritisneš na gumb, vendar ne na gumb za zapiranje gumba". Pa potem tudi gumba za zapiranje gumba ne rabiš.

**Comment by jureslak** [comment]
Ok, to je bila tudi moja prva ideja, edini problem je da ni prostora za footer. 
Ali ga hočeš stlačit pod urnik, to bi se tudi pomoje dalo, samo bo na majhno? 

![image](https://user-images.githubusercontent.com/1394590/33516367-ef3206e6-d771-11e7-8cf8-3d148cd9d68b.png)

**Comment by matijapretnar** [comment]
Kaj pa, če je footer samo na dnu prve strani?

Razmišljam, da bi prvo stran poenostavili. Dva ali trije stolpci bi bili urniki smeri, ki se jih rabi direktno, v zadnjem bi bilo pa iskanje po osebah in učilnicah ter povezava do sestavljenih urnikov, rezervacij, iskanja prostih učilnic, … Potem bi bila tudi prva stran toliko krajša, da bi kdo celo kdaj videl footer. Drugače pa ni hude škode tudi, če se ga večinoma ne vidi.

**Comment by jureslak** [comment]
Hmm, človek želi sporočit napako ko jo vidi, tako da je fino da je to takoj pri roki (zato je bila moja prva ideja fixed gumb). Zdaj ko gledam tale footer pod urnikom se mi ne zdi tako napačen, pa lepo je da imajo strani footer, ki pove kdo je lastnik ipd. Je pa na splošno na urniku prostora, tudi za gumb "natisni" iz #11 in "označi več" na prvi strani. Ta za natistnit bi lahko bil zgoraj desno, pa je potem tudi bug report lahko zraven?

Na prvi strani je pa meni všeč, da so smei in učilnice zlistane, ker jih ni tako veliko. P tudi za osebe nimam nič proti, samo da so tudi searcheable. Iz tega opisa si ne predstavljam dovolj dobro, kako bi nova stran zgledala, da bi lahko karkoli rekel. Zdi se mi prav, da bi lahko od kjerkoli prišel do rezervacij, urnika, prostih učilnic ipd., ne samo iz prve strani (v primeru da bi se te stvari premaknile iz menija na prvo stran).
