### ISSUE TITLE
Spletni obrazec za rezervacije

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/urnik#2]
Fino bi bilo, da se ljudje lahko sami prijavijo in vnašajo rezervacije.

**Comment by suhogrozdje** [comment]
Razmišljal sem o sledečem vmesniku. Asistentu, ki želi na začetku 1. semestra rezervirati učilnice za kolokvija in izpite (tudi tistega jeseni), je ponavadi pomembno kdaj bo napravil rezervacijo do enega tedna natančno. Pomembno mu je tudi kako velika je učilnica in če je fizikalna, matematična ali računalniška. Vse to je možno že na strani s prostimi učilnicami, zato je smiselen začetek stvaritve rezervacije prav tam. Po izbiri tedna in filtriranju poišče in klikne na željeno učilnico.

Klik na učilnico ga pripelje na stran tedna za to učilnico, ki vključuje poleg srečanj tudi vse rezervacije v tej učilnici v izbranem tednu (i.e. url bi izgledal nekako tako: _/ucilnica/1/rezervacije/2018-02-05_, kjer datum na koncu označuje izbran teden). Ta stran torej prikazuje srečanja tistega tedna (če je izbran teden znotraj datumskega razpona trenutnega semestra), pa tudi rezervacije v tistem tednu. Ker je (če je) uporabnik avtenticiran, ima ob strani pregleda tedna kartico z gumbom "Ustvari rezervacijo", ki se po kliku spremeni v "Klikni željeno uro" (hover čez prosto uro povzroči spremembo backgrounda za tisto uro in nek "+" v sredini pravokotnika). Ko klikne na prosto uro, uporabnika to vodi na formo z izbiro imena in trajanja rezervacije (default 2 uri), ki ni v administraciji, temveč na neki novi strani. Če je izbral trajanje predolgo ali ga je nekdo prehitel pri rezervaciji tiste ure, rezervacija ni možna, prikazan je nek message. 

Avtenticiran uporabnik naj ima poleg takšnega create postopka na voljo prav celoten CRUD sistem, vendar je Update in Delete na voljo le za rezervacije, ki pripadajo njemu. To naj bo prisotno na neki novi strani, denimo "/account/rezervacije/" ali pač karkoli temu podobnega.

PS: na strani s prostimi učilnicami je potrebno spremeniti tudi stransko kartico z izbiro tedna, da prikaže _vse_ tedne v trenutnem študijskem letu (tj. od 1. oktobra tekočega študijskega leta do 1. oktobra naslednjega študijskega leta), namesto da pokaže le tedne, v kateri so rezervacije že bile narejene. To lahko napravi obstoječ dropdown malo predolg - morda je bolje to napraviti s [Select2](https://select2.org/getting-started/basic-usage).

Nadaljnji predlogi, opombe, itd. so seveda zaželjene.

**Comment by jureslak** [comment]
Glede prvega, na strani za proste učilnice je točno to že planirano: glej `_proste_ucilnice_za_termin.html`:
```
{% if stanje == 'prosta' %}
              <a href="{% url 'urnik_ucilnice' ucilnica.pk %}">Učilnica {{ ucilnica.oznaka }}</a>
              je prosta v {{ termin.dan|dan_tozilnik }} ob {{ termin.ura }}ih.
              {#  TODO: odkomentiraj ko bo narejen obrazec za rezervacije  #}
{# <a href="#" class="nobr">Rezerviraj <i class="material-icons">open_in_new</i></a>#}
```

Tisti dolg select se lahko odpravi tudi tako, da če v nekem tednu pač ni nobene rezervacije, človek rezervira na splošnem tednu, in potem ročno vnese dan na naslednji strani.

O ostalem bo pa več povedal Matija.
