### ISSUE TITLE
Pripombe na nov videz urnika

### ISSUE THREAD

**Issue by matijapretnar** [ul-fmf/urnik#28]
Anita Bartol mi je poslala sledeče pripombe:

- [ ] v Internet Explorerju je prikaz urnika obupen
- [x] ni mi všeč, ker so izvajalci na dnu strani, prej je bilo bolje
- [x] "prijavi napako" - hitra povezava (še) ne deluje
- [x] "navodila in pomoč" - hitra povezava (še) ne deluje
- [x] če si prijavljen v urejanju, se še vedno prikažejo vse rezervacije od oktobra 2017 dalje

**Comment by jureslak** [comment]
Hitre povezave so bile popravljene v #18.

Ostalo bom pa pogledal. Za izvajalce najbrž misli pri sestavljenem urniku?

**Comment by jureslak** [comment]
Tega z rezervacijami ne morem reproducat, meni se seznam na strani vedno prične od zdaj naprej.

**Comment by matijapretnar** [comment]
Verjetno je tu mišljen Django admin.

**Comment by jureslak** [comment]
Ah, to pa ni tako trivialno rešljivo. Za IE tudi ne morem reproducat, je bil to morda samo caching issue in še ni naloadal novega css-a? Jaz sem se potrudil in odprl v IE in Edgu, pa je zgledalo normalno.

**Comment by matijapretnar** [comment]
Django admin sem popravil.
