### ISSUE TITLE
"Sestavljen urnik"

### ISSUE THREAD

**Issue by andrejbauer** [ul-fmf/urnik#31]
Fraza "sestavljen urnik" je vsaj meni misteriozna in nerazumljiva. V kombinaciji z izbiro "domov" je uporabnik pred zanimivo uganko: kje je "dom" in kaj pomeni, da je urnik "setavljen"?

Predlagam, da se spremeni nekako takole:

1. Namesto izbire "domov" v menuju, naj zgoraj levo piše "Urnik", ki pelje na osnovno stran. Ful je obupno, da kliknem zgoraj levo in dobim menu, ker imajo vsi web sajti na tem svetu zgoraj levo link na "osnovno stran". Ikono za menu poznamo vsi, so nam jo vsilili, tako da je potem lahko takoj zraven ali spodaj. S tem se v menuju tudi znebimo linka na "domov" (če pa že bo, naj se imenuje "Urnik").

2. Namesto "sestavljen urnik" naj piše "kombiniran pogled" ali kaj takega, da se bo dejansko vedelo, da uporabnik tu *izbira pogled*. Jaz na primer sem mislil, da "sestavljen urnik" pomeni "urnik, ki sta ga sestavila sestavljalca urnika".

**Comment by andrejbauer** [comment]
P.S. Če se bo "sestavljen urnik" preimenovalo, je treba preimenovati tudi na strani "Domov".

**Comment by matijapretnar** [comment]
Closed by #34.
