### ISSUE TITLE
Nekaj hroščev

### ISSUE THREAD

**Issue by suhogrozdje** [ul-fmf/urnik#37]
Pozdravljeni sodelujoči v repozitoriju,
pri raziskovanju funkcionalnosti urnika sem opazil 2 buga, oba na isti strani za proste učilnice:

- [Prvi](https://urnik.fmf.uni-lj.si/proste/?pz=True&teden=2018-02-05&tip=M) ima opraviti z dejstvom, da se v tekočem tednu še ne izvajajo srečanja, medtem ko stran s prostimi učilnicami pravi, da se (npr. hover čez učilnico 2.02 v četrtek ob 10),
- Drugi bug se zdi malenkost hujši, gre za prekrivanje rezervacije in srečanja. Spet glej učilnico 2.02 ob 10ih v četrtek (v tednu kasneje kot v prvem primeru, t.j. že znotraj novega semestra), [ko je vključena opcija "pokaži zasedene"](https://urnik.fmf.uni-lj.si/proste/?pz=True&teden=2018-02-12&tip=M) in [ko je vključena opcija "pokaži rezervirane"](https://urnik.fmf.uni-lj.si/proste/?pr=True&teden=2018-02-12&tip=M). V prvem primeru je prisotno srečanje za predmet Finančna matematika 1 (izvaja Nika Novak), v drugem pa je rezervacija "Izpit NTF" (Pino Koc). [Edit: 2. semester se začne z 19. februarjem, torej to ni težava.]

Še ena manjša opomba:
- na [strani s pomočjo](https://urnik.fmf.uni-lj.si/help/#primer-uporabe) je prisotna slika nedavno izbrisane opcije "Ignoriraj urnik" in njene uporabe.

Da ne izpostavljam samo napak, sem pripravljen tudi pomagat. Imam izkušnje z MVC frameworki (sicer ne z Djangom, delal sem z Laravelom, sem pa domač v Pythonu) in frontendom. Opazil sem, da bi bilo potrebno celostno porihtat rezervacije (#2 in #6) in začel malce razvijat logiko za tem (kako avtenticirat nekoga z @fmf.uni-lj.si mailom, da ima moč urejati svoje rezervacije). Da ne razvijam logike v prazno, bi mogoče rabil izmenjat par besed okrog tega z razvijalcem projekta, če je interes za to prisoten.

**Comment by suhogrozdje** [comment]
Sumim, da je drugi bug nastal tako, da je Pino Koc že nekaj časa nazaj napravil rezervacijo, ki se je ob formaciji srečanj za 2. semester prekrila s srečanjem Finančna matematika 1, ki je takrat nastalo. To utegne biti težava v naslednjem tednu, če se bo to zgodilo večkrat in bo nek razred prišel na srečanje predmeta v isto učilnico, kot bodo v njej nekateri imeli izpit.

**Comment by matijapretnar** [comment]
Najlepša hvala za opozorilo. Zdaj bi morali biti popravljeni obe stvari.

Ja, pomoč bo vsekakor dobrodošla! Specifično z avtentikacijo FMF uporabnikov se ni treba ukvarjati, ker sem že v dveh Django aplikacijah usposobil avtentikacijo prek univerzitetnega LDAPa. Tisto, kar je treba urediti, je splošen uporabniški vmesnik za rezervacije. Če bo enkrat pripeljan do te točke, da dela za ročno ustvarjene uporabnike, lahko ostalo pripeljem do konca sam. Diskusijo lahko nadaljujeva v npr. #2 in #6 ali pa enkrat v živo.
