### ISSUE TITLE
Pravilne velikosti učilnic

### ISSUE THREAD

**Issue by jureslak** [ul-fmf/urnik#47]
Trenutne velikosti učilnic na urniku ne odražajo dejanskega števila stolov in imajo zgodovinske vrednosti 41, 42, 43 in 44. Ker baza zdaj podpira več učilnic z enakim številom mest, lahko posodobimo te podatke na prave vrednosti.

**Comment by matijapretnar** [comment]
Če kdo semle napiše pravilne velikosti, jih bom popravil v bazi. Da ne bo treba fizično hoditi naokoli, se lahko pogleda tudi sedežne rede na https://github.com/ul-fmf/izpit - po https://github.com/ul-fmf/izpit/issues/10 sodeč bi morali tam biti pravilni.

**Comment by matijapretnar** [comment]
[ucilnice.pdf](https://github.com/ul-fmf/urnik/files/2695539/ucilnice.pdf)

**Comment by nikerzetic** [comment]
Število sedežev v učilnicah, glede na profesorjev pdf. V .txt formatu, ker GitHub ne podpira .csv datotek v komentarjih.
[stevilo_sedezev.txt](https://github.com/ul-fmf/urnik/files/2716492/stevilo_sedezev.txt)

**Comment by matijapretnar** [comment]
Sem vnesel. Najlepša hvala!
