### ISSUE TITLE
404 ob poskusu dodajanja rezervacije pred prijavo

### ISSUE THREAD

**Issue by jaanos** [ul-fmf/urnik#61]
Če uporabnik ni prijavljen in s strani [rezervacij](https://urnik.fmf.uni-lj.si/rezervacije/) klikne na povezavo za [novo rezervacijo](https://urnik.fmf.uni-lj.si/nova-rezervacija/), se naredi redirect na `https://urnik.fmf.uni-lj.si/accounts/login/?next=/nova-rezervacija/`, ki pa ne obstaja (pravi naslov je brez `accounts/`).

Mimogrede, obrazec za rezervacije ima trenutno naslov *Poletni semester 2018/19*, kar najbrž ni najbolj ustrezno.

**Comment by jureslak** [comment]
Hvala, to sem že nekoč popravil, pa sem potem spreminjal login URL. Ker ni zelo kritično, pa lušno za popravit, bi pustil ta issue odprt za programerski klub :)
