### ISSUE TITLE
Kombiniranje predmetov v kombiniranem pogledu

### ISSUE THREAD

**Issue by StrahR** [ul-fmf/urnik#86]
Fino bi bilo, če bi se dalo v kombiniranem pogledu izbrati posamezne predmete:

![kombiniran_pogled](https://user-images.githubusercontent.com/45151812/74990500-c1409a80-5443-11ea-97cf-afe775dbd729.png)

Kolikor sem slišal od @matijapretnar je problem s številom predmetov, pa še kar precej jih je posebnih (govorilne ure, kolokviji, …), kar bi delalo probleme z uporabniškim vmesnikom.

Če ima kdo kak predlog, bi bil zelo dobrodošel.

**Comment by jureslak** [comment]
Ja, edini smiseln uporabniški vmesnik, ki ga jaz vidim, ki bil pillbox (https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox), ki bi ga v resnici lahko imeli tudi za izvajalce, ker tisti seznam je že zdaj neprijetno dolg...

To sicer da dependency na še en javascript library, ampak ni tako hudo, glede na to da nanj dependa tudi django sam za točno tak vmesnik v admin interfaceu.

**Comment by StrahR** [comment]
To mi je všeč, edino kar ostane bi potem bilo filtriranje, saj zgleda, kot da je v bazi precej odvečnih predmetov (recimo id=472 in 499 sta duplikata 166 in 167). Poskusil sem filtrirati po številu srečanj (torej da prikaže zgolj predmete, ki imajo srečanja) vendar se mi zdi da je vseeno par čudnih predmetov ostane (pa na primer ne vidim Fizike 2 od MAT-2).

Naj za backend del naredim PR, glede na to, da imam že narejeno?

**Comment by jureslak** [comment]
Sorry, ker je malo trajalo, sem se moral zmenit na faksu kako tocno poteka development na urniku. Lahko narediš PR, bom pogledaj kako izgleda.

Glede podatkov na urniku pa ja, če imaš kokretne stvari, mi jih lahko pošlješ (ali pa se naredi issue), pa sem bom potem enkrat oglasil v referatu, da se popravijo.

**Comment by StrahR** [comment]
Dobro, PR bom naredil malo kasneje.

Za konkretne stvari ne vem, ker delam na tisti anonimirani bazi, če se pa predmeti ne odstanjujeo iz baze vsak semester, sem opazil za vsaj id 166 in 167, Algebra 1 za finančnike in matematike 1 letnik.

Bom jutri malo bolje pogledal kako zgelda baza, da vidim kako se bi dalo filtrirati.
